Fixed auth import for user
This test was failing because the user model changed in my commit.

Now it fails because of a dataset issue:

(venv) C:\dev\codalab>python codalab\manage.py test web
No module named debug_toolbar
Creating test database for alias 'default'...
E
======================================================================
ERROR: test_add_participant (apps.web.tests.SimpleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\dev\codalab\codalab\apps\web\tests.py", line 18, in setUp
management.call_command('create_competition', title='Test Title',
description='Test Description',creator=self.user.email)
File
"C:\dev\codalab\venv\lib\site-packages\django\core\management\__init__.py",
line 147, in call_command
klass = load_command_class(app_name, name)
File
"C:\dev\codalab\venv\lib\site-packages\django\core\management\__init__.py",
line 77, in load_command_class
module = import_module('%s.management.commands.%s' % (app_name, name))
File "C:\dev\codalab\venv\lib\site-packages\django\utils\importlib.py",
line 35, in import_module
__import__(name)
File
"C:\dev\codalab\codalab\apps\web\management\commands\create_competition.py",
line 3, in <module>
from apps.web.models import
Competition,CompetitionPhase,CompetitionDataset,CompetitionParticipant,ExternalFile,ExternalFileType,ParticipantStatus
ImportError: cannot import name CompetitionDataset

----------------------------------------------------------------------
Ran 1 test in 0.009s

FAILED (errors=1)
Destroying test database for alias 'default'...